variables:
  REACT_APP_AZURE_ACCESS_TOKEN_FUNCTION_URL: https://get-me-access-token.com
  REACT_APP_GITHUB_CLIENT_ID: abcde

stages:
  - stage: verify
    jobs:
      - job: lint
        steps:
          - template: install-steps.yml
          - script: npm run lint
            displayName: Run TSLint
            workingDirectory: frontend

      - job: build
        steps:
          - template: install-steps.yml
          - script: npm run build
            displayName: Build the project
            workingDirectory: frontend

      - job: test_frontend
        variables:
          CI: true
        steps:
          - template: install-steps.yml
          - script: npm run test
            displayName: Test the frontend
            workingDirectory: frontend
